name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
    matrix:
    node-version: [18.x]
    steps:
      - users: actions/checkout@v3
      - name: Starting Node.js ${{matrix.nose-version}}
        uses: action/setup-node@v3
        with:
          node-version: ${{matrix.nose-version}}
      - name: install modules
        run: yarn add
      - name: build project
        run: yarn build
