name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{matrix.node-version}}
        uses: action/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: install modules
        run: yarn add
      - name: build project
        run: yarn build
